from .punto1 import graficar_genero
from .punto2 import graficar_porcentaje
from .punto3 import grafico_dias
from .punto4 import promedio_fechas
from .punto5 import mejores
from .punto6 import estadistica_6
from .punto7 import estadistica_7
from .punto8 import estadistica_8
from .punto9 import estadistica_9
